# Github CI/CD Project: 

name: Hello World Pipeline Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Step-0: Fetch'
      uses: actions/checkout@v3
      #-------------------------------------------------------
    - name: 'Step-1: Set up JDK 8'
      uses: actions/setup-java@v1
      with:
        java-version: '8'
      #-------------------------------------------------------
    - name: 'Step-2: Update POM Version'
      run: mvn validate -DbumpPatch -f ./my-app/pom.xml 
      #-------------------------------------------------------
    - name: 'Step-3: Build with Maven'
      run: mvn -B clean package --file ./my-app/pom.xml
      #-------------------------------------------------------
    - name: 'Step-4: Set up Docker Buildx'
      uses: docker/setup-buildx-action@v2
      #------------------------------------------------------- 
    - name: 'Step-5: Login to DockerHub'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      #-------------------------------------------------------   
    - name: 'Step-6: Build Image and Push'
      env:
         version: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ./my-app/pom.xml)
         name: $(mvn help:evaluate -Dexpression=project.name -q -DforceStdout --file ./my-app/pom.xml)
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java:v${{ env.version }} \
        --build-arg version=${{ env.version }} \
        --build-arg app_name=${{ env.name }} \
        -f ./Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/java:v${{ env.version }}     
      #------------------------------------------------------- 
      
###############################################################################
#                                   EOF                                       #
###############################################################################
      
      
      
      
